version: "3.8"

services:
    mymongodb:
        image: "mongo"
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "ananas"
            MONGO_INITDB_ROOT_PASSWORD: "12345"
        command: mongod --quiet --logpath /dev/null

    backend:
        build:
            context: "backend/"
            dockerfile: "Dockerfile"
        restart: always
        ports:
            - 8080:8080
        environment:
            PORT: 8080
            MONGODB_PORT: 3000
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - "$PWD/backend:/backend"

    #frontend:
    #    build: ./frontend
    #    ports:
    #        - "3000:3000"
    #    volumes:
    #        - ./frontend/src:/app/src
    #    stdin_open: true
    #    tty: true
    #    depends_on:
    #        - backend
volumes:
    data:
